CREATE TABLE IF NOT EXISTS trucks (
  id UUID PRIMARY KEY,
  plate VARCHAR(10) NOT NULL UNIQUE,
  carrier VARCHAR(100) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS docks (
  id SERIAL PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE'
);

CREATE TABLE IF NOT EXISTS dock_schedules (
  id UUID PRIMARY KEY,
  truck_id UUID NOT NULL REFERENCES trucks(id),
  dock_id INTEGER NOT NULL REFERENCES docks(id),
  status VARCHAR(30) NOT NULL DEFAULT 'CONFIRMED',
  logical_clock INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_events (
  id UUID PRIMARY KEY,
  event_id UUID NOT NULL,
  worker_id VARCHAR(30) NOT NULL,
  event_type VARCHAR(100) NOT NULL,
  logical_clock INTEGER NOT NULL,
  payload JSONB NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO docks (code, status)
VALUES
  ('DOCA-01', 'AVAILABLE'),
  ('DOCA-02', 'AVAILABLE'),
  ('DOCA-03', 'AVAILABLE')
ON CONFLICT (code) DO NOTHING;